#!/bin/zsh

if [ -z $1 ]; then
    charset="[:digit:]"
else
    charset=$1
fi

if [ -z $2 ]; then
    digit=10
else
    digit=$2
fi

result=`cat /dev/urandom 2>/dev/null | tr -cd $charset 2>/dev/null | head -c $digit 2>/dev/null`

echo $result
